name: ETL to CSV

# Workflow triggers
on:
  schedule:
    - cron: "0 2 * * *"  # Runs at 2am UTC every day
  workflow_dispatch:  # Allows manual triggering of the workflow
  push:
    branches:
      - 'main'

jobs:
  csv-etl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Fetch and transform data
        run: |
          python src/to_gh_artifact.py

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: etl-address-data
          path: output.csv